jobs:
  cs-kubernetes:
    image: registry.erda.cloud/erda-actions/cs-kubernetes:3.20
    resources:
      cpu: 0.2
      mem: 128
    binds:
    - ((storageMountPoint))/dice-ops/ecluster-configs:/opt/ecluster-configs:rw
