### job 配置项
jobs:
  agent:
    image: registry.erda.cloud/erda-actions/action-agent:3.21-20210322-891e3565d
    labels:
      # 必填字段
      MD5: 775229abe45f90fdfd8b47771b636c60
    envs:
      # DEBUG mode, will produce more logs
      DEBUG: false
      # push log to collector
      ENABLE_PUSH_LOG_TO_COLLECTOR: false
