### job 配置项
jobs:
  js:
    image: registry.erda.cloud/erda-actions/js-script-action:20200525-401ee62
    envs:
      BP_DOCKER_BASE_REGISTRY: registry.erda.cloud
    resources:
      cpu: 1
      mem: 2048
