### job 配置项
jobs:
  js:
    image: registry.erda.cloud/erda-actions/js-action:20210609-398d3be
    envs:
      BP_DOCKER_BASE_REGISTRY: registry.erda.cloud
    resources:
      cpu: 1
      mem: 2048
