### job 配置项
jobs:
  jsonparse:
    image: registry.erda.cloud/erda-actions/jsonparse-action:20210420-92996b4
    envs:
      BP_DOCKER_BASE_REGISTRY: registry.erda.cloud
    resources:
      cpu: 0.1
      mem: 200
